{{ config (
  materialized= 'view',
  schema= 'DOORDASH',
  tags= ["staging","daily"]
)
}}

WITH source AS (
  SELECT * FROM  {{source('TEST_SCHEMA_EXT_DEV','DOORDASH_RAW')}}
),
rename AS 
(
SELECT DISTINCT 
  MD5(S.ORDER_ID) AS K_ORDER_DLHK  
  ,MD5(CONCAT(COALESCE(S.EMPLOYEE_NAME,''),'-',COALESCE(S.EMPLOYEE_EMAIL,''))) AS K_EMPLOYEE_DLHK
  ,MD5(S.CURRENCY) AS K_CURRENCY_DLHK
  ,MD5(S.BUDGET_ID) AS K_BUDGET_DLHK
  ,MD5(S.MERCHANT) AS K_MERCHANT_DLHK
  ,MD5(S.TEAM_ACCOUNT) AS K_TEAM_ACCOUNT_DLHK
  ,MD5(DELIVERY_ADDRESS) AS K_DELIVERY_ADDRESS_DLHK
  ,ORDER_ID AS K_ORDER_BK
  ,DELIVERY_DATE AS A_DELIVERY_DATE
  ,DELIVERY_TIME AS A_DELIVERY_TIME
  ,PICKUP_DELIVERY AS A_PICKUP_DELIVERY
  ,EXPENSE_CODE AS A_EXPENSE_CODE
  ,EXPENSE_NOTES AS A_EXPENSE_NOTE
  ,SUBTOTAL AS M_SUBTOTAL
  ,TAX AS M_TAX
  ,TIP AS M_TIP
  ,SERVICE_FEE AS M_SERVICE_FEE
  ,DELIVERY_FEE AS M_DELIVERY_FEE
  ,LEGISLATIVE_FEE AS M_LEGISLATIVE_FEE
  ,SMALL_ORDER_FEE AS M_SMALL_ORDER_FEE
  ,DISCOUNTS_PROMOTIONS AS M_DISCOUNTS_PROMOTIONS
  ,ORDER_TOTAL AS M_ORDER_TOTAL
  ,COMPANY_PAID AS M_COMPANY_PAID
  ,EMPLOYEE_PAID AS M_EMPLOYEE_PAID

FROM 
  source S
)

SELECT * FROM rename