{{ config (
  materialized= 'view',
  schema= 'DOORDASH',
  tags= ["staging","daily"]
)
}}

WITH source AS (
  SELECT * FROM  {{source('TEST_SCHEMA_EXT_DEV','DOORDASH_RAW')}}
),
weather AS (
  SELECT * FROM  {{ref('V_WEATHER_CONDITIONS_STG')}}
),
delivery_address AS (
  SELECT * FROM  {{ ref('V_DELIVERY_ADDRESS_STG') }}
),
rename AS 
(
SELECT DISTINCT 
  MD5(S.ORDER_ID) AS K_ORDER_DLHK  
  ,MD5(CONCAT(COALESCE(S.EMPLOYEE_NAME,''),'-',COALESCE(S.EMPLOYEE_EMAIL,''))) AS K_EMPLOYEE_DLHK
  ,MD5(S.CURRENCY) AS K_CURRENCY_DLHK
  ,MD5(S.BUDGET_ID) AS K_BUDGET_DLHK
  ,MD5(S.MERCHANT) AS K_MERCHANT_DLHK
  ,MD5(S.TEAM_ACCOUNT) AS K_TEAM_ACCOUNT_DLHK
  ,MD5(S.DELIVERY_ADDRESS) AS K_DELIVERY_ADDRESS_DLHK
  ,S.ORDER_ID AS K_ORDER_BK
  ,S.DELIVERY_DATE AS A_DELIVERY_DATE
  ,S.DELIVERY_TIME AS A_DELIVERY_TIME
  ,S.PICKUP_DELIVERY AS A_PICKUP_DELIVERY
  ,S.EXPENSE_CODE AS A_EXPENSE_CODE
  ,S.EXPENSE_NOTES AS A_EXPENSE_NOTE
  ,W.A_WEATHER_CONDITION_SUMMARY
  ,W.A_AVG_TEMPERATURE_SUMMARY
  ,S.SUBTOTAL AS M_SUBTOTAL
  ,S.TAX AS M_TAX
  ,S.TIP AS M_TIP
  ,S.SERVICE_FEE AS M_SERVICE_FEE
  ,S.DELIVERY_FEE AS M_DELIVERY_FEE
  ,S.LEGISLATIVE_FEE AS M_LEGISLATIVE_FEE
  ,S.SMALL_ORDER_FEE AS M_SMALL_ORDER_FEE
  ,S.DISCOUNTS_PROMOTIONS AS M_DISCOUNTS_PROMOTIONS
  ,S.ORDER_TOTAL AS M_ORDER_TOTAL
  ,S.COMPANY_PAID AS M_COMPANY_PAID
  ,S.EMPLOYEE_PAID AS M_EMPLOYEE_PAID
FROM 
  source S
  LEFT JOIN delivery_address A ON A.K_DELIVERY_ADDRESS_DLHK = MD5(S.DELIVERY_ADDRESS)
  LEFT JOIN weather W on W.K_WEATHER_DLHK = MD5(A.K_COUNTRY_POSTALCODE_BK||'-'||TRIM(S.DELIVERY_DATE))
)

SELECT * FROM rename