{{ config (
  materialized= 'view',
  schema= var('target_schema','STRIPE'),
  tags= ["staging","daily"]
)
}}

WITH payment_intent AS (
  SELECT * FROM  {{source(var('source_schema', 'DEMO_STRIPE_NEW'), 'PAYMENT_INTENT')}}
),
rename AS 
(
SELECT  
  --DLHK
  MD5(ID) AS K_PAYMENT_INTENT_DLHK
  ,MD5(ON_BEHALF_OF) AS K_ON_BEHALF_OF_ACCOUNT_DLHK
  ,MD5(CUSTOMER) AS K_CUSTOMER_DLHK
  ,MD5(INVOICE) AS K_INVOICE_DLHK
  ,MD5(PAYMENT_METHOD) AS K_PAYMENT_METHOD_DLHK  
  --BUSINESS KEYS
  ,ID AS K_PAYMENT_INTENT_BK
  ,CUSTOMER AS K_CUSTOMER_BK
  ,ON_BEHALF_OF AS K_ON_BEHALF_OF_ACCOUNT_BK
  ,INVOICE AS K_INVOICE_BK
  ,PAYMENT_METHOD AS K_PAYMENT_METHOD_BK  
  --ATTRIBUTES
  ,APPLICATION AS A_APPLICATION
  ,CAPTURE_METHOD AS A_CAPTURE_METHOD
  ,CHARGES_URL AS A_CHARGES_URL  
  ,CLIENT_SECRET AS A_CLIENT_SECRET
  ,CONFIRMATION_METHOD AS A_CONFIRMATION_METHOD
  ,CREATED AS A_CREATED_AT
  ,CURRENCY AS A_CURRENCY  
  ,DESCRIPTION AS A_DESCRIPTION  
  ,LAST_PAYMENT_ERROR_CODE AS A_LAST_PAYMENT_ERROR_CODE
  ,LAST_PAYMENT_ERROR_TYPE AS A_LAST_PAYMENT_ERROR_TYPE
  ,NEXT_ACTION AS A_NEXT_ACTION 
  ,PAYMENT_METHOD_TYPES AS A_PAYMENT_METHOD_TYPES
  ,RECEIPT_EMAIL AS A_RECEIPT_EMAIL
  ,REVIEW AS A_REVIEW
  ,SETUP_FUTURE_USAGE AS A_SETUP_FUTURE_USAGE
  ,SHIPPING_ADDRESS AS A_SHIPPING_ADDRESS
  ,SHIPPING_CARRIER AS A_SHIPPING_CARRIER
  ,SHIPPING_NAME AS A_SHIPPING_NAME
  ,SHIPPING_PHONE AS A_SHIPPING_PHONE
  ,SHIPPING_TRACKING_NUMBER AS A_SHIPPING_TRACKING_NUMBER
  ,STATEMENT_DESCRIPTOR AS A_STATEMENT_DESCRIPTOR
  ,STATEMENT_DESCRIPTOR_SUFFIX AS A_STATEMENT_DESCRIPTOR_SUFFIX
  ,STATUS AS A_STATUS
  ,CANCELED_AT AS A_CANCELED_AT
  ,CANCELLATION_REASON AS A_CANCELLATION_REASON
  ,TRANSFER_DATA AS A_TRANSFER_DATA
  ,TRANSFER_GROUP AS A_TRANSFER_GROUP  
  ,CHARGES_HAS_MORE AS B_CHARGES_HAS_MORE
  ,LIVEMODE AS B_LIVEMODE
  --METRICS
  ,DIV0(AMOUNT,100) AS M_AMOUNT
  ,DIV0(AMOUNT_CAPTURABLE,100) AS M_AMOUNT_CAPTURABLE
  ,DIV0(AMOUNT_RECEIVED,100) AS M_AMOUNT_RECEIVED
  ,DIV0(APPLICATION_FEE_AMOUNT,100) AS M_APPLICATION_FEE_AMOUNT
  --METADATA
  , '{{invocation_id}}' as MD_INTGR_ID
  , CURRENT_TIMESTAMP() MD_ELT_UPDATED_DTS
FROM 
  payment_intent P
)

SELECT * FROM rename