{{ config (
  materialized= 'view',
  schema= var('target_schema','STRIPE'),
  tags= ["staging","daily"]
)
}}

WITH refund AS (
  SELECT * FROM  {{source(var('source_schema', 'DEMO_STRIPE_NEW'), 'REFUND')}}
),
rename AS 
(
SELECT  
  --DLHK  
  MD5(ID) AS K_REFUND_DLHK
  ,MD5(TRIM(BALANCE_TRANSACTION)) AS K_BALANCE_TRANSACTION_DLHK
  ,MD5(TRIM(CHARGE)) AS K_CHARGE_DLHK
  ,MD5(REPLACE(TRIM(PAYMENT_INTENT), '"','')) AS K_PAYMENT_INTENT_DLHK
  --BUSINESS KEYS
  ,ID AS K_REFUND_BK
  ,TRIM(BALANCE_TRANSACTION) AS K_BALANCE_TRANSACTION_BK
  ,TRIM(CHARGE) AS K_CHARGE_BK
  ,REPLACE(TRIM(PAYMENT_INTENT), '"','') AS K_PAYMENT_INTENT_BK
  --ATTRIBUTES  
  ,CREATED AS A_CREATED_AT
  ,CURRENCY AS A_CURRENCY
  ,DESCRIPTION AS A_DESCRIPTION
  ,METADATA AS A_METADATA  
  ,REASON AS A_REASON
  ,RECEIPT_NUMBER AS A_RECEIPT_NUMBER
  ,STATUS AS A_STATUS
  --METRICS
  ,DIV0(AMOUNT,100) AS M_AMOUNT
  --METADATA
  , '{{invocation_id}}' as MD_INTGR_ID
  , CURRENT_TIMESTAMP() MD_ELT_UPDATED_DTS
FROM 
  refund P
)

SELECT * FROM rename