{{ config (
  materialized= 'view',
  schema= var('target_schema','STRIPE'),
  tags= ["staging","daily"]
)
}}

WITH credit_note AS (
  SELECT * FROM  {{ref('V_STR_CREDIT_NOTE_HEADER_STG')}}
),
credit_note_item AS (
  SELECT * FROM  {{ref('V_STR_CREDIT_NOTE_LINE_ITEM_STG')}}
),
rename AS 
(
SELECT  
    --DLHK
    CI.K_CREDIT_NOTE_ITEM_DLHK
    ,C.K_CREDIT_NOTE_DLHK
    ,C.K_CUSTOMER_DLHK
    --BK
    ,C.K_CREDIT_NOTE_BK
    ,C.K_CUSTOMER_BK
    ,C.K_INVOICE_BK
    ,C.K_REFUND_BK
    ,C.K_CUSTOMER_BALANCE_TRANSACTION_BK
    ,K_K_CREDIT_NOTE_ITEM_BK
    --ATTRIBUTES
    ,C.A_CREATED_AT
    ,C.A_CREATED_AT::DATE AS A_CREATED_DATE_AT
    ,C.A_CREDIT_NOTE_TYPE
    ,C.A_CURRENCY    
    ,C.A_MEMO
    ,C.A_NUMBER
    ,C.A_OUT_OF_BAND_AMOUNT
    ,C.A_PDF
    ,C.A_REASON
    ,C.A_STATUS
    ,CI.A_DESCRIPTION  AS A_ITEM_DESCRIPTION  
    ,CI.A_UNIT_AMOUNT_DECIMAL AS A_ITEM_UNIT_AMOUNT_DECIMAL
    --BOOLEAN
    ,C.B_LIVEMODE AS B_CREDIT_NOTE_LIVEMODE
    ,B_LIVEMODE  AS B_ITEM_LIVEMODE  
    --METRICS
    ,CI.M_AMOUNT AS M_ITEM_AMOUNT
    ,CI.M_DISCOUNT_AMOUNT AS M_ITEM_DISCOUNT_AMOUNT
    ,CI.M_QUANTITY AS M_ITEM_QUANTITY
    ,CI.M_UNIT_AMOUNT AS M_ITEM_UNIT_AMOUNT
  --METADATA
  , '{{invocation_id}}' as MD_INTGR_ID
  , CURRENT_TIMESTAMP() MD_ELT_UPDATED_DTS
FROM 
  credit_note C
  LEFT JOIN credit_note_item CI ON C.K_CREDIT_NOTE_DLHK = CI.K_CREDIT_NOTE_DLHK
)

SELECT * FROM rename