 {{ config(
    materialized='view',    
    schema='DOORDASH',
    enabled=var('include_third_party_data_weather__weathersource')
) }}


SELECT 'Afghanistan' as A_COUNTRY_NAME, 'AF' as A_ALPHA2_COUNTRY_CODE, 'AFG' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Albania' as A_COUNTRY_NAME, 'AL' as A_ALPHA2_COUNTRY_CODE, 'ALB' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Algeria' as A_COUNTRY_NAME, 'DZ' as A_ALPHA2_COUNTRY_CODE, 'DZA' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'American Samoa' as A_COUNTRY_NAME, 'AS' as A_ALPHA2_COUNTRY_CODE, 'ASM' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Andorra' as A_COUNTRY_NAME, 'AD' as A_ALPHA2_COUNTRY_CODE, 'AND' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Angola' as A_COUNTRY_NAME, 'AO' as A_ALPHA2_COUNTRY_CODE, 'AGO' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Anguilla' as A_COUNTRY_NAME, 'AI' as A_ALPHA2_COUNTRY_CODE, 'AIA' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Antarctica' as A_COUNTRY_NAME, 'AQ' as A_ALPHA2_COUNTRY_CODE, 'ATA' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Antigua and Barbuda' as A_COUNTRY_NAME, 'AG' as A_ALPHA2_COUNTRY_CODE, 'ATG' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Argentina' as A_COUNTRY_NAME, 'AR' as A_ALPHA2_COUNTRY_CODE, 'ARG' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Armenia' as A_COUNTRY_NAME, 'AM' as A_ALPHA2_COUNTRY_CODE, 'ARM' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Aruba' as A_COUNTRY_NAME, 'AW' as A_ALPHA2_COUNTRY_CODE, 'ABW' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Australia' as A_COUNTRY_NAME, 'AU' as A_ALPHA2_COUNTRY_CODE, 'AUS' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Austria' as A_COUNTRY_NAME, 'AT' as A_ALPHA2_COUNTRY_CODE, 'AUT' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Azerbaijan' as A_COUNTRY_NAME, 'AZ' as A_ALPHA2_COUNTRY_CODE, 'AZE' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Bahamas' as A_COUNTRY_NAME, 'BS' as A_ALPHA2_COUNTRY_CODE, 'BHS' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Bahrain' as A_COUNTRY_NAME, 'BH' as A_ALPHA2_COUNTRY_CODE, 'BHR' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Bangladesh' as A_COUNTRY_NAME, 'BD' as A_ALPHA2_COUNTRY_CODE, 'BGD' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Barbados' as A_COUNTRY_NAME, 'BB' as A_ALPHA2_COUNTRY_CODE, 'BRB' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Belarus' as A_COUNTRY_NAME, 'BY' as A_ALPHA2_COUNTRY_CODE, 'BLR' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Belgium' as A_COUNTRY_NAME, 'BE' as A_ALPHA2_COUNTRY_CODE, 'BEL' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Belize' as A_COUNTRY_NAME, 'BZ' as A_ALPHA2_COUNTRY_CODE, 'BLZ' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Benin' as A_COUNTRY_NAME, 'BJ' as A_ALPHA2_COUNTRY_CODE, 'BEN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Bermuda' as A_COUNTRY_NAME, 'BM' as A_ALPHA2_COUNTRY_CODE, 'BMU' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Bhutan' as A_COUNTRY_NAME, 'BT' as A_ALPHA2_COUNTRY_CODE, 'BTN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Bolivia, Plurinational State of' as A_COUNTRY_NAME, 'BO' as A_ALPHA2_COUNTRY_CODE, 'BOL' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Bolivia' as A_COUNTRY_NAME, 'BO' as A_ALPHA2_COUNTRY_CODE, 'BOL' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Bosnia and Herzegovina' as A_COUNTRY_NAME, 'BA' as A_ALPHA2_COUNTRY_CODE, 'BIH' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Botswana' as A_COUNTRY_NAME, 'BW' as A_ALPHA2_COUNTRY_CODE, 'BWA' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Bouvet Island' as A_COUNTRY_NAME, 'BV' as A_ALPHA2_COUNTRY_CODE, 'BVT' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Brazil' as A_COUNTRY_NAME, 'BR' as A_ALPHA2_COUNTRY_CODE, 'BRA' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'British Indian Ocean Territory' as A_COUNTRY_NAME, 'IO' as A_ALPHA2_COUNTRY_CODE, 'IOT' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Brunei Darussalam' as A_COUNTRY_NAME, 'BN' as A_ALPHA2_COUNTRY_CODE, 'BRN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Brunei' as A_COUNTRY_NAME, 'BN' as A_ALPHA2_COUNTRY_CODE, 'BRN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Bulgaria' as A_COUNTRY_NAME, 'BG' as A_ALPHA2_COUNTRY_CODE, 'BGR' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Burkina Faso' as A_COUNTRY_NAME, 'BF' as A_ALPHA2_COUNTRY_CODE, 'BFA' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Burundi' as A_COUNTRY_NAME, 'BI' as A_ALPHA2_COUNTRY_CODE, 'BDI' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Cambodia' as A_COUNTRY_NAME, 'KH' as A_ALPHA2_COUNTRY_CODE, 'KHM' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Cameroon' as A_COUNTRY_NAME, 'CM' as A_ALPHA2_COUNTRY_CODE, 'CMR' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Canada' as A_COUNTRY_NAME, 'CA' as A_ALPHA2_COUNTRY_CODE, 'CAN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Cape Verde' as A_COUNTRY_NAME, 'CV' as A_ALPHA2_COUNTRY_CODE, 'CPV' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Cayman Islands' as A_COUNTRY_NAME, 'KY' as A_ALPHA2_COUNTRY_CODE, 'CYM' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Central African Republic' as A_COUNTRY_NAME, 'CF' as A_ALPHA2_COUNTRY_CODE, 'CAF' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Chad' as A_COUNTRY_NAME, 'TD' as A_ALPHA2_COUNTRY_CODE, 'TCD' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Chile' as A_COUNTRY_NAME, 'CL' as A_ALPHA2_COUNTRY_CODE, 'CHL' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'China' as A_COUNTRY_NAME, 'CN' as A_ALPHA2_COUNTRY_CODE, 'CHN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Christmas Island' as A_COUNTRY_NAME, 'CX' as A_ALPHA2_COUNTRY_CODE, 'CXR' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Cocos (Keeling) Islands' as A_COUNTRY_NAME, 'CC' as A_ALPHA2_COUNTRY_CODE, 'CCK' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Colombia' as A_COUNTRY_NAME, 'CO' as A_ALPHA2_COUNTRY_CODE, 'COL' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Comoros' as A_COUNTRY_NAME, 'KM' as A_ALPHA2_COUNTRY_CODE, 'COM' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Congo' as A_COUNTRY_NAME, 'CG' as A_ALPHA2_COUNTRY_CODE, 'COG' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Congo, the Democratic Republic of the' as A_COUNTRY_NAME, 'CD' as A_ALPHA2_COUNTRY_CODE, 'COD' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Cook Islands' as A_COUNTRY_NAME, 'CK' as A_ALPHA2_COUNTRY_CODE, 'COK' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Costa Rica' as A_COUNTRY_NAME, 'CR' as A_ALPHA2_COUNTRY_CODE, 'CRI' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Côte d''Ivoire' as A_COUNTRY_NAME, 'CI' as A_ALPHA2_COUNTRY_CODE, 'CIV' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Ivory Coast' as A_COUNTRY_NAME, 'CI' as A_ALPHA2_COUNTRY_CODE, 'CIV' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Croatia' as A_COUNTRY_NAME, 'HR' as A_ALPHA2_COUNTRY_CODE, 'HRV' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Cuba' as A_COUNTRY_NAME, 'CU' as A_ALPHA2_COUNTRY_CODE, 'CUB' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Cyprus' as A_COUNTRY_NAME, 'CY' as A_ALPHA2_COUNTRY_CODE, 'CYP' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Czech Republic' as A_COUNTRY_NAME, 'CZ' as A_ALPHA2_COUNTRY_CODE, 'CZE' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Denmark' as A_COUNTRY_NAME, 'DK' as A_ALPHA2_COUNTRY_CODE, 'DNK' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Djibouti' as A_COUNTRY_NAME, 'DJ' as A_ALPHA2_COUNTRY_CODE, 'DJI' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Dominica' as A_COUNTRY_NAME, 'DM' as A_ALPHA2_COUNTRY_CODE, 'DMA' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Dominican Republic' as A_COUNTRY_NAME, 'DO' as A_ALPHA2_COUNTRY_CODE, 'DOM' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Ecuador' as A_COUNTRY_NAME, 'EC' as A_ALPHA2_COUNTRY_CODE, 'ECU' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Egypt' as A_COUNTRY_NAME, 'EG' as A_ALPHA2_COUNTRY_CODE, 'EGY' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'El Salvador' as A_COUNTRY_NAME, 'SV' as A_ALPHA2_COUNTRY_CODE, 'SLV' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Equatorial Guinea' as A_COUNTRY_NAME, 'GQ' as A_ALPHA2_COUNTRY_CODE, 'GNQ' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Eritrea' as A_COUNTRY_NAME, 'ER' as A_ALPHA2_COUNTRY_CODE, 'ERI' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Estonia' as A_COUNTRY_NAME, 'EE' as A_ALPHA2_COUNTRY_CODE, 'EST' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Ethiopia' as A_COUNTRY_NAME, 'ET' as A_ALPHA2_COUNTRY_CODE, 'ETH' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Falkland Islands (Malvinas)' as A_COUNTRY_NAME, 'FK' as A_ALPHA2_COUNTRY_CODE, 'FLK' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Faroe Islands' as A_COUNTRY_NAME, 'FO' as A_ALPHA2_COUNTRY_CODE, 'FRO' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Fiji' as A_COUNTRY_NAME, 'FJ' as A_ALPHA2_COUNTRY_CODE, 'FJI' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Finland' as A_COUNTRY_NAME, 'FI' as A_ALPHA2_COUNTRY_CODE, 'FIN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'France' as A_COUNTRY_NAME, 'FR' as A_ALPHA2_COUNTRY_CODE, 'FRA' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'French Guiana' as A_COUNTRY_NAME, 'GF' as A_ALPHA2_COUNTRY_CODE, 'GUF' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'French Polynesia' as A_COUNTRY_NAME, 'PF' as A_ALPHA2_COUNTRY_CODE, 'PYF' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'French Southern Territories' as A_COUNTRY_NAME, 'TF' as A_ALPHA2_COUNTRY_CODE, 'ATF' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Gabon' as A_COUNTRY_NAME, 'GA' as A_ALPHA2_COUNTRY_CODE, 'GAB' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Gambia' as A_COUNTRY_NAME, 'GM' as A_ALPHA2_COUNTRY_CODE, 'GMB' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Georgia' as A_COUNTRY_NAME, 'GE' as A_ALPHA2_COUNTRY_CODE, 'GEO' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Germany' as A_COUNTRY_NAME, 'DE' as A_ALPHA2_COUNTRY_CODE, 'DEU' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Ghana' as A_COUNTRY_NAME, 'GH' as A_ALPHA2_COUNTRY_CODE, 'GHA' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Gibraltar' as A_COUNTRY_NAME, 'GI' as A_ALPHA2_COUNTRY_CODE, 'GIB' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Greece' as A_COUNTRY_NAME, 'GR' as A_ALPHA2_COUNTRY_CODE, 'GRC' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Greenland' as A_COUNTRY_NAME, 'GL' as A_ALPHA2_COUNTRY_CODE, 'GRL' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Grenada' as A_COUNTRY_NAME, 'GD' as A_ALPHA2_COUNTRY_CODE, 'GRD' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Guadeloupe' as A_COUNTRY_NAME, 'GP' as A_ALPHA2_COUNTRY_CODE, 'GLP' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Guam' as A_COUNTRY_NAME, 'GU' as A_ALPHA2_COUNTRY_CODE, 'GUM' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Guatemala' as A_COUNTRY_NAME, 'GT' as A_ALPHA2_COUNTRY_CODE, 'GTM' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Guernsey' as A_COUNTRY_NAME, 'GG' as A_ALPHA2_COUNTRY_CODE, 'GGY' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Guinea' as A_COUNTRY_NAME, 'GN' as A_ALPHA2_COUNTRY_CODE, 'GIN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Guinea-Bissau' as A_COUNTRY_NAME, 'GW' as A_ALPHA2_COUNTRY_CODE, 'GNB' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Guyana' as A_COUNTRY_NAME, 'GY' as A_ALPHA2_COUNTRY_CODE, 'GUY' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Haiti' as A_COUNTRY_NAME, 'HT' as A_ALPHA2_COUNTRY_CODE, 'HTI' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Heard Island and McDonald Islands' as A_COUNTRY_NAME, 'HM' as A_ALPHA2_COUNTRY_CODE, 'HMD' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Holy See (Vatican City State)' as A_COUNTRY_NAME, 'VA' as A_ALPHA2_COUNTRY_CODE, 'VAT' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Honduras' as A_COUNTRY_NAME, 'HN' as A_ALPHA2_COUNTRY_CODE, 'HND' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Hong Kong' as A_COUNTRY_NAME, 'HK' as A_ALPHA2_COUNTRY_CODE, 'HKG' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Hungary' as A_COUNTRY_NAME, 'HU' as A_ALPHA2_COUNTRY_CODE, 'HUN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Iceland' as A_COUNTRY_NAME, 'IS' as A_ALPHA2_COUNTRY_CODE, 'ISL' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'India' as A_COUNTRY_NAME, 'IN' as A_ALPHA2_COUNTRY_CODE, 'IND' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Indonesia' as A_COUNTRY_NAME, 'ID' as A_ALPHA2_COUNTRY_CODE, 'IDN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Iran, Islamic Republic of' as A_COUNTRY_NAME, 'IR' as A_ALPHA2_COUNTRY_CODE, 'IRN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Iraq' as A_COUNTRY_NAME, 'IQ' as A_ALPHA2_COUNTRY_CODE, 'IRQ' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Ireland' as A_COUNTRY_NAME, 'IE' as A_ALPHA2_COUNTRY_CODE, 'IRL' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Isle of Man' as A_COUNTRY_NAME, 'IM' as A_ALPHA2_COUNTRY_CODE, 'IMN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Israel' as A_COUNTRY_NAME, 'IL' as A_ALPHA2_COUNTRY_CODE, 'ISR' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Italy' as A_COUNTRY_NAME, 'IT' as A_ALPHA2_COUNTRY_CODE, 'ITA' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Jamaica' as A_COUNTRY_NAME, 'JM' as A_ALPHA2_COUNTRY_CODE, 'JAM' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Japan' as A_COUNTRY_NAME, 'JP' as A_ALPHA2_COUNTRY_CODE, 'JPN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Jersey' as A_COUNTRY_NAME, 'JE' as A_ALPHA2_COUNTRY_CODE, 'JEY' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Jordan' as A_COUNTRY_NAME, 'JO' as A_ALPHA2_COUNTRY_CODE, 'JOR' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Kazakhstan' as A_COUNTRY_NAME, 'KZ' as A_ALPHA2_COUNTRY_CODE, 'KAZ' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Kenya' as A_COUNTRY_NAME, 'KE' as A_ALPHA2_COUNTRY_CODE, 'KEN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Kiribati' as A_COUNTRY_NAME, 'KI' as A_ALPHA2_COUNTRY_CODE, 'KIR' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Korea, Democratic People''s Republic of' as A_COUNTRY_NAME, 'KP' as A_ALPHA2_COUNTRY_CODE, 'PRK' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Korea, Republic of' as A_COUNTRY_NAME, 'KR' as A_ALPHA2_COUNTRY_CODE, 'KOR' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'South Korea' as A_COUNTRY_NAME, 'KR' as A_ALPHA2_COUNTRY_CODE, 'KOR' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Kuwait' as A_COUNTRY_NAME, 'KW' as A_ALPHA2_COUNTRY_CODE, 'KWT' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Kyrgyzstan' as A_COUNTRY_NAME, 'KG' as A_ALPHA2_COUNTRY_CODE, 'KGZ' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Lao People''s Democratic Republic' as A_COUNTRY_NAME, 'LA' as A_ALPHA2_COUNTRY_CODE, 'LAO' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Latvia' as A_COUNTRY_NAME, 'LV' as A_ALPHA2_COUNTRY_CODE, 'LVA' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Lebanon' as A_COUNTRY_NAME, 'LB' as A_ALPHA2_COUNTRY_CODE, 'LBN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Lesotho' as A_COUNTRY_NAME, 'LS' as A_ALPHA2_COUNTRY_CODE, 'LSO' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Liberia' as A_COUNTRY_NAME, 'LR' as A_ALPHA2_COUNTRY_CODE, 'LBR' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Libyan Arab Jamahiriya' as A_COUNTRY_NAME, 'LY' as A_ALPHA2_COUNTRY_CODE, 'LBY' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Libya' as A_COUNTRY_NAME, 'LY' as A_ALPHA2_COUNTRY_CODE, 'LBY' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Liechtenstein' as A_COUNTRY_NAME, 'LI' as A_ALPHA2_COUNTRY_CODE, 'LIE' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Lithuania' as A_COUNTRY_NAME, 'LT' as A_ALPHA2_COUNTRY_CODE, 'LTU' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Luxembourg' as A_COUNTRY_NAME, 'LU' as A_ALPHA2_COUNTRY_CODE, 'LUX' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Macao' as A_COUNTRY_NAME, 'MO' as A_ALPHA2_COUNTRY_CODE, 'MAC' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Macedonia, the former Yugoslav Republic of' as A_COUNTRY_NAME, 'MK' as A_ALPHA2_COUNTRY_CODE, 'MKD' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Madagascar' as A_COUNTRY_NAME, 'MG' as A_ALPHA2_COUNTRY_CODE, 'MDG' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Malawi' as A_COUNTRY_NAME, 'MW' as A_ALPHA2_COUNTRY_CODE, 'MWI' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Malaysia' as A_COUNTRY_NAME, 'MY' as A_ALPHA2_COUNTRY_CODE, 'MYS' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Maldives' as A_COUNTRY_NAME, 'MV' as A_ALPHA2_COUNTRY_CODE, 'MDV' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Mali' as A_COUNTRY_NAME, 'ML' as A_ALPHA2_COUNTRY_CODE, 'MLI' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Malta' as A_COUNTRY_NAME, 'MT' as A_ALPHA2_COUNTRY_CODE, 'MLT' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Marshall Islands' as A_COUNTRY_NAME, 'MH' as A_ALPHA2_COUNTRY_CODE, 'MHL' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Martinique' as A_COUNTRY_NAME, 'MQ' as A_ALPHA2_COUNTRY_CODE, 'MTQ' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Mauritania' as A_COUNTRY_NAME, 'MR' as A_ALPHA2_COUNTRY_CODE, 'MRT' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Mauritius' as A_COUNTRY_NAME, 'MU' as A_ALPHA2_COUNTRY_CODE, 'MUS' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Mayotte' as A_COUNTRY_NAME, 'YT' as A_ALPHA2_COUNTRY_CODE, 'MYT' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Mexico' as A_COUNTRY_NAME, 'MX' as A_ALPHA2_COUNTRY_CODE, 'MEX' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Micronesia, Federated States of' as A_COUNTRY_NAME, 'FM' as A_ALPHA2_COUNTRY_CODE, 'FSM' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Moldova, Republic of' as A_COUNTRY_NAME, 'MD' as A_ALPHA2_COUNTRY_CODE, 'MDA' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Monaco' as A_COUNTRY_NAME, 'MC' as A_ALPHA2_COUNTRY_CODE, 'MCO' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Mongolia' as A_COUNTRY_NAME, 'MN' as A_ALPHA2_COUNTRY_CODE, 'MNG' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Montenegro' as A_COUNTRY_NAME, 'ME' as A_ALPHA2_COUNTRY_CODE, 'MNE' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Montserrat' as A_COUNTRY_NAME, 'MS' as A_ALPHA2_COUNTRY_CODE, 'MSR' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Morocco' as A_COUNTRY_NAME, 'MA' as A_ALPHA2_COUNTRY_CODE, 'MAR' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Mozambique' as A_COUNTRY_NAME, 'MZ' as A_ALPHA2_COUNTRY_CODE, 'MOZ' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Myanmar' as A_COUNTRY_NAME, 'MM' as A_ALPHA2_COUNTRY_CODE, 'MMR' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Burma' as A_COUNTRY_NAME, 'MM' as A_ALPHA2_COUNTRY_CODE, 'MMR' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Namibia' as A_COUNTRY_NAME, 'NA' as A_ALPHA2_COUNTRY_CODE, 'NAM' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Nauru' as A_COUNTRY_NAME, 'NR' as A_ALPHA2_COUNTRY_CODE, 'NRU' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Nepal' as A_COUNTRY_NAME, 'NP' as A_ALPHA2_COUNTRY_CODE, 'NPL' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Netherlands' as A_COUNTRY_NAME, 'NL' as A_ALPHA2_COUNTRY_CODE, 'NLD' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Netherlands Antilles' as A_COUNTRY_NAME, 'AN' as A_ALPHA2_COUNTRY_CODE, 'ANT' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'New Caledonia' as A_COUNTRY_NAME, 'NC' as A_ALPHA2_COUNTRY_CODE, 'NCL' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'New Zealand' as A_COUNTRY_NAME, 'NZ' as A_ALPHA2_COUNTRY_CODE, 'NZL' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Nicaragua' as A_COUNTRY_NAME, 'NI' as A_ALPHA2_COUNTRY_CODE, 'NIC' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Niger' as A_COUNTRY_NAME, 'NE' as A_ALPHA2_COUNTRY_CODE, 'NER' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Nigeria' as A_COUNTRY_NAME, 'NG' as A_ALPHA2_COUNTRY_CODE, 'NGA' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Niue' as A_COUNTRY_NAME, 'NU' as A_ALPHA2_COUNTRY_CODE, 'NIU' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Norfolk Island' as A_COUNTRY_NAME, 'NF' as A_ALPHA2_COUNTRY_CODE, 'NFK' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Northern Mariana Islands' as A_COUNTRY_NAME, 'MP' as A_ALPHA2_COUNTRY_CODE, 'MNP' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Norway' as A_COUNTRY_NAME, 'NO' as A_ALPHA2_COUNTRY_CODE, 'NOR' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Oman' as A_COUNTRY_NAME, 'OM' as A_ALPHA2_COUNTRY_CODE, 'OMN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Pakistan' as A_COUNTRY_NAME, 'PK' as A_ALPHA2_COUNTRY_CODE, 'PAK' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Palau' as A_COUNTRY_NAME, 'PW' as A_ALPHA2_COUNTRY_CODE, 'PLW' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Palestinian Territory, Occupied' as A_COUNTRY_NAME, 'PS' as A_ALPHA2_COUNTRY_CODE, 'PSE' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Panama' as A_COUNTRY_NAME, 'PA' as A_ALPHA2_COUNTRY_CODE, 'PAN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Papua New Guinea' as A_COUNTRY_NAME, 'PG' as A_ALPHA2_COUNTRY_CODE, 'PNG' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Paraguay' as A_COUNTRY_NAME, 'PY' as A_ALPHA2_COUNTRY_CODE, 'PRY' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Peru' as A_COUNTRY_NAME, 'PE' as A_ALPHA2_COUNTRY_CODE, 'PER' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Philippines' as A_COUNTRY_NAME, 'PH' as A_ALPHA2_COUNTRY_CODE, 'PHL' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Pitcairn' as A_COUNTRY_NAME, 'PN' as A_ALPHA2_COUNTRY_CODE, 'PCN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Poland' as A_COUNTRY_NAME, 'PL' as A_ALPHA2_COUNTRY_CODE, 'POL' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Portugal' as A_COUNTRY_NAME, 'PT' as A_ALPHA2_COUNTRY_CODE, 'PRT' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Puerto Rico' as A_COUNTRY_NAME, 'PR' as A_ALPHA2_COUNTRY_CODE, 'PRI' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Qatar' as A_COUNTRY_NAME, 'QA' as A_ALPHA2_COUNTRY_CODE, 'QAT' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Réunion' as A_COUNTRY_NAME, 'RE' as A_ALPHA2_COUNTRY_CODE, 'REU' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Romania' as A_COUNTRY_NAME, 'RO' as A_ALPHA2_COUNTRY_CODE, 'ROU' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Russian Federation' as A_COUNTRY_NAME, 'RU' as A_ALPHA2_COUNTRY_CODE, 'RUS' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Russia' as A_COUNTRY_NAME, 'RU' as A_ALPHA2_COUNTRY_CODE, 'RUS' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Rwanda' as A_COUNTRY_NAME, 'RW' as A_ALPHA2_COUNTRY_CODE, 'RWA' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Saint Helena, Ascension and Tristan da Cunha' as A_COUNTRY_NAME, 'SH' as A_ALPHA2_COUNTRY_CODE, 'SHN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Saint Kitts and Nevis' as A_COUNTRY_NAME, 'KN' as A_ALPHA2_COUNTRY_CODE, 'KNA' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Saint Lucia' as A_COUNTRY_NAME, 'LC' as A_ALPHA2_COUNTRY_CODE, 'LCA' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Saint Pierre and Miquelon' as A_COUNTRY_NAME, 'PM' as A_ALPHA2_COUNTRY_CODE, 'SPM' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Saint Vincent and the Grenadines' as A_COUNTRY_NAME, 'VC' as A_ALPHA2_COUNTRY_CODE, 'VCT' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Saint Vincent & the Grenadines' as A_COUNTRY_NAME, 'VC' as A_ALPHA2_COUNTRY_CODE, 'VCT' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'St. Vincent and the Grenadines' as A_COUNTRY_NAME, 'VC' as A_ALPHA2_COUNTRY_CODE, 'VCT' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Samoa' as A_COUNTRY_NAME, 'WS' as A_ALPHA2_COUNTRY_CODE, 'WSM' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'San Marino' as A_COUNTRY_NAME, 'SM' as A_ALPHA2_COUNTRY_CODE, 'SMR' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Sao Tome and Principe' as A_COUNTRY_NAME, 'ST' as A_ALPHA2_COUNTRY_CODE, 'STP' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Saudi Arabia' as A_COUNTRY_NAME, 'SA' as A_ALPHA2_COUNTRY_CODE, 'SAU' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Senegal' as A_COUNTRY_NAME, 'SN' as A_ALPHA2_COUNTRY_CODE, 'SEN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Serbia' as A_COUNTRY_NAME, 'RS' as A_ALPHA2_COUNTRY_CODE, 'SRB' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Seychelles' as A_COUNTRY_NAME, 'SC' as A_ALPHA2_COUNTRY_CODE, 'SYC' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Sierra Leone' as A_COUNTRY_NAME, 'SL' as A_ALPHA2_COUNTRY_CODE, 'SLE' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Singapore' as A_COUNTRY_NAME, 'SG' as A_ALPHA2_COUNTRY_CODE, 'SGP' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Slovakia' as A_COUNTRY_NAME, 'SK' as A_ALPHA2_COUNTRY_CODE, 'SVK' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Slovenia' as A_COUNTRY_NAME, 'SI' as A_ALPHA2_COUNTRY_CODE, 'SVN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Solomon Islands' as A_COUNTRY_NAME, 'SB' as A_ALPHA2_COUNTRY_CODE, 'SLB' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Somalia' as A_COUNTRY_NAME, 'SO' as A_ALPHA2_COUNTRY_CODE, 'SOM' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'South Africa' as A_COUNTRY_NAME, 'ZA' as A_ALPHA2_COUNTRY_CODE, 'ZAF' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'South Georgia and the South Sandwich Islands' as A_COUNTRY_NAME, 'GS' as A_ALPHA2_COUNTRY_CODE, 'SGS' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'South Sudan' as A_COUNTRY_NAME, 'SS' as A_ALPHA2_COUNTRY_CODE, 'SSD' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Spain' as A_COUNTRY_NAME, 'ES' as A_ALPHA2_COUNTRY_CODE, 'ESP' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Sri Lanka' as A_COUNTRY_NAME, 'LK' as A_ALPHA2_COUNTRY_CODE, 'LKA' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Sudan' as A_COUNTRY_NAME, 'SD' as A_ALPHA2_COUNTRY_CODE, 'SDN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Suriname' as A_COUNTRY_NAME, 'SR' as A_ALPHA2_COUNTRY_CODE, 'SUR' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Svalbard and Jan Mayen' as A_COUNTRY_NAME, 'SJ' as A_ALPHA2_COUNTRY_CODE, 'SJM' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Swaziland' as A_COUNTRY_NAME, 'SZ' as A_ALPHA2_COUNTRY_CODE, 'SWZ' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Sweden' as A_COUNTRY_NAME, 'SE' as A_ALPHA2_COUNTRY_CODE, 'SWE' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Switzerland' as A_COUNTRY_NAME, 'CH' as A_ALPHA2_COUNTRY_CODE, 'CHE' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Syrian Arab Republic' as A_COUNTRY_NAME, 'SY' as A_ALPHA2_COUNTRY_CODE, 'SYR' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Taiwan, Province of China' as A_COUNTRY_NAME, 'TW' as A_ALPHA2_COUNTRY_CODE, 'TWN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Taiwan' as A_COUNTRY_NAME, 'TW' as A_ALPHA2_COUNTRY_CODE, 'TWN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Tajikistan' as A_COUNTRY_NAME, 'TJ' as A_ALPHA2_COUNTRY_CODE, 'TJK' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Tanzania, United Republic of' as A_COUNTRY_NAME, 'TZ' as A_ALPHA2_COUNTRY_CODE, 'TZA' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Thailand' as A_COUNTRY_NAME, 'TH' as A_ALPHA2_COUNTRY_CODE, 'THA' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Timor-Leste' as A_COUNTRY_NAME, 'TL' as A_ALPHA2_COUNTRY_CODE, 'TLS' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Togo' as A_COUNTRY_NAME, 'TG' as A_ALPHA2_COUNTRY_CODE, 'TGO' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Tokelau' as A_COUNTRY_NAME, 'TK' as A_ALPHA2_COUNTRY_CODE, 'TKL' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Tonga' as A_COUNTRY_NAME, 'TO' as A_ALPHA2_COUNTRY_CODE, 'TON' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Trinidad and Tobago' as A_COUNTRY_NAME, 'TT' as A_ALPHA2_COUNTRY_CODE, 'TTO' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Tunisia' as A_COUNTRY_NAME, 'TN' as A_ALPHA2_COUNTRY_CODE, 'TUN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Turkey' as A_COUNTRY_NAME, 'TR' as A_ALPHA2_COUNTRY_CODE, 'TUR' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Turkmenistan' as A_COUNTRY_NAME, 'TM' as A_ALPHA2_COUNTRY_CODE, 'TKM' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Turks and Caicos Islands' as A_COUNTRY_NAME, 'TC' as A_ALPHA2_COUNTRY_CODE, 'TCA' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Tuvalu' as A_COUNTRY_NAME, 'TV' as A_ALPHA2_COUNTRY_CODE, 'TUV' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Uganda' as A_COUNTRY_NAME, 'UG' as A_ALPHA2_COUNTRY_CODE, 'UGA' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Ukraine' as A_COUNTRY_NAME, 'UA' as A_ALPHA2_COUNTRY_CODE, 'UKR' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'United Arab Emirates' as A_COUNTRY_NAME, 'AE' as A_ALPHA2_COUNTRY_CODE, 'ARE' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'United Kingdom' as A_COUNTRY_NAME, 'GB' as A_ALPHA2_COUNTRY_CODE, 'GBR' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'United States' as A_COUNTRY_NAME, 'US' as A_ALPHA2_COUNTRY_CODE, 'USA' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'United States Minor Outlying Islands' as A_COUNTRY_NAME, 'UM' as A_ALPHA2_COUNTRY_CODE, 'UMI' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Uruguay' as A_COUNTRY_NAME, 'UY' as A_ALPHA2_COUNTRY_CODE, 'URY' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Uzbekistan' as A_COUNTRY_NAME, 'UZ' as A_ALPHA2_COUNTRY_CODE, 'UZB' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Vanuatu' as A_COUNTRY_NAME, 'VU' as A_ALPHA2_COUNTRY_CODE, 'VUT' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Venezuela, Bolivarian Republic of' as A_COUNTRY_NAME, 'VE' as A_ALPHA2_COUNTRY_CODE, 'VEN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Venezuela' as A_COUNTRY_NAME, 'VE' as A_ALPHA2_COUNTRY_CODE, 'VEN' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Viet Nam' as A_COUNTRY_NAME, 'VN' as A_ALPHA2_COUNTRY_CODE, 'VNM' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Vietnam' as A_COUNTRY_NAME, 'VN' as A_ALPHA2_COUNTRY_CODE, 'VNM' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Virgin Islands, British' as A_COUNTRY_NAME, 'VG' as A_ALPHA2_COUNTRY_CODE, 'VGB' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Virgin Islands, U.S.' as A_COUNTRY_NAME, 'VI' as A_ALPHA2_COUNTRY_CODE, 'VIR' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Wallis and Futuna' as A_COUNTRY_NAME, 'WF' as A_ALPHA2_COUNTRY_CODE, 'WLF' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Western Sahara' as A_COUNTRY_NAME, 'EH' as A_ALPHA2_COUNTRY_CODE, 'ESH' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Yemen' as A_COUNTRY_NAME, 'YE' as A_ALPHA2_COUNTRY_CODE, 'YEM' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Zambia' as A_COUNTRY_NAME, 'ZM' as A_ALPHA2_COUNTRY_CODE, 'ZMB' as A_ALPHA3_COUNTRY_CODE  UNION ALL
SELECT 'Zimbabwe' as A_COUNTRY_NAME, 'ZW' as A_ALPHA2_COUNTRY_CODE, 'ZWE' as A_ALPHA3_COUNTRY_CODE 