{{ config (
  materialized= 'view',
  schema= 'DOORDASH',
  tags= ["staging","daily"]
)
}}

WITH source AS (
  SELECT * FROM  {{source('TEST_SCHEMA_EXT_DEV','DOORDASH_RAW')}}
),
(
SELECT DISTINCT 
    MD5(DELIVERY_ADDRESS) AS K_DELIVERY_ADDRESS_DLHK
    ,TRIM(SPLIT_PART(DELIVERY_ADDRESS, ',', 4))||'-'||TRIM(H.POSTAL_CODE)  AS K_COUNTRY_POSTALCODE_BK
    ,MD5(TRIM(C.A_ALPHA3_COUNTRY_CODE)||'-'||TRIM(H.POSTAL_CODE)||'-'||H.DATE_VALID_STD)
    ,TRIM(SPLIT_PART(DELIVERY_ADDRESS, ',', 1)) AS A_DELIVERY_STREET
    ,TRIM(SPLIT_PART(DELIVERY_ADDRESS, ',', 2)) AS A_DELIVERY_CITY
    ,TRIM(SPLIT_PART(TRIM(SPLIT_PART(DELIVERY_ADDRESS, ',', 3)),' ',1)) AS A_DELIVERY_STATE
    ,TRIM(SPLIT_PART(TRIM(SPLIT_PART(DELIVERY_ADDRESS, ',', 3)),' ',2)) AS A_DELIVERY_POSTALCODE
    ,TRIM(SPLIT_PART(DELIVERY_ADDRESS, ',', 4)) AS A_DELIVERY_COUNTRY
FROM 
  source
WHERE 
   DELIVERY_ADDRESS IS NOT NULL
)

SELECT * FROM rename