version: 2

sources:      
  - name: "{{ var('source_schema')}}"
    database: "{{ var('source_database')}}"
    schema: "{{ var('source_schema')}}"
    quoting:
      identifier: true
    tables:
      - name: DOORDASH_RAW      

  - name: "{{ var('source_weather_schema')}}"
    description: Snowflake's sample weather data from marketplace
    database: "{{ var('source_weather_database')}}"
    schema: "{{ var('source_weather_schema')}}"
    tables:
      - name: HISTORY_DAY


