version: 2

sources:      
  - name: "{{ var('source_schema', 'DEMO_STRIPE_NEW')}}"
    database: "{{ var('source_database', 'DEVELOPER_SANDBOX')}}"
    schema: "{{ var('source_schema', 'DEMO_STRIPE_NEW')}}"
    quoting:
      identifier: true
    tables:
      - name: BALANCE_TRANSACTION
      - name: CHARGE
      - name: CUSTOMER
      - name: PAYMENT_INTENT
      - name: PAYMENT_METHOD
      - name: PAYMENT_METHOD_CARD
      - name: PAYOUT
      #- name: REFUND
      #- name: CARD
      #- name: PLANS
      - name: INVOICE
      - name: INVOICE_LINE_ITEM
      - name: SUBSCRIPTION
      - name: SUBSCRIPTION_ITEM
      - name: STRIPE_ORDER
      - name: ORDER_ITEM
      - name: ORDER_RETURN
      - name: ORDER_RETURN_ITEM