{{ config (
  materialized= 'view',
  schema= var('target_schema'),
  tags= ["staging","daily"]
)
}}

WITH payout AS (
  SELECT * FROM  {{source(var('source_schema', 'DEMO_STRIPE_NEW'), 'PAYOUT')}}
),
rename AS 
(
SELECT  
  --DLHK
  MD5(ID) AS K_PAYOUT_DLHK 
  ,MD5(BALANCE_TRANSACTION_ID) AS K_BALANCE_TRANSACTION_DLHK
  ,MD5(FAILURE_BALANCE_TRANSACTION_ID) AS K_FAILURE_BALANCE_TRANSACTION_DLHK
  --BUSINESS KEYS
  ,ID AS K_PAYOUT_BK
  ,BALANCE_TRANSACTION_ID AS K_BALANCE_TRANSACTION_BK
  ,FAILURE_BALANCE_TRANSACTION_ID AS K_FAILURE_BALANCE_TRANSACTION_BK  
  --ATTRIBUTES
  ,ARRIVAL_DATE AS A_ARRIVAL_DATE
  ,CREATED AS A_CREATED_AT
  ,CURRENCY AS A_CURRENCY
  ,DESCRIPTION AS A_DESCRIPTION
  ,FAILURE_CODE AS A_FAILURE_CODE
  ,FAILURE_MESSAGE AS A_FAILURE_MESSAGE
  ,METHOD AS A_METHOD
  ,SOURCE_TYPE AS A_SOURCE_TYPE
  ,STATEMENT_DESCRIPTOR AS A_STATEMENT_DESCRIPTOR
  ,STATUS AS A_STATUS
  ,TYPE AS A_TYPE
  --BOOLEAN  
  ,AUTOMATIC AS B_AUTOMATIC
  ,LIVEMODE AS B_LIVEMODE
  --AMOUNT
  ,AMOUNT AS M_AMOUNT
  --METADATA
  , '{{invocation_id}}' as MD_INTGR_ID
  , CURRENT_TIMESTAMP() MD_ELT_UPDATED_DTS
FROM 
  payout P
)

SELECT * FROM rename