{{ config (
  materialized= 'view',
  schema= var('target_schema'),
  tags= ["staging","daily"]
)
}}

WITH customer AS (
  SELECT * FROM  {{source(var('source_schema', 'DEMO_STRIPE_NEW'), 'CUSTOMER')}}
),

rename AS 
(
SELECT  
  --DLHK
  MD5(ID) AS K_CUSTOMER_DLHK
  --Business keys
  ,ID AS K_CUSTOMER_BK  
  ,INVOICE_SETTINGS_DEFAULT_PAYMENT_METHOD AS K_DEFAULT_PAYMENT_METHOD_BK
  --attributes
  ,ADDRESS_CITY AS A_ADDRESS_CITY
  ,ADDRESS_COUNTRY AS A_ADDRESS_COUNTRY
  ,CREATED::TIMESTAMP AS A_CREATED_AT
  ,CURRENCY AS A_CURRENCY
  ,DEFAULT_SOURCE AS A_DEFAULT_SOURCE
  ,DESCRIPTION AS A_DESCRIPTION
  ,EMAIL AS A_EMAIL
  ,INVOICE_PREFIX AS A_INVOICE_PREFIX
  ,INVOICE_SETTINGS_CUSTOM_FIELDS AS A_INVOICE_SETTINGS_CUSTOM_FIELDS  
  ,INVOICE_SETTINGS_FOOTER AS A_INVOICE_SETTINGS_FOOTER
  ,NAME AS A_NAME
  ,PHONE AS A_PHONE
  ,PREFERRED_LOCALES AS A_PREFERRED_LOCALES
  ,SHIPPING_ADDRESS_CITY AS A_SHIPPING_ADDRESS_CITY
  ,SHIPPING_ADDRESS_COUNTRY AS A_SHIPPING_ADDRESS_COUNTRY
  ,TAX_EXEMPT AS A_TAX_EXEMPT  
  --BOOLEAN
  ,DELINQUENT AS B_DELINQUENT
  ,LIVEMODE AS B_LIVEMODE
  --METRICS
  ,BALANCE AS M_BALANCE
  --METADATA
  , '{{invocation_id}}' as MD_INTGR_ID
  , CURRENT_TIMESTAMP() MD_ELT_UPDATED_DTS
FROM 
  customer 
)

SELECT * FROM rename