{{ config (
  materialized= 'view',
  schema= var('target_schema'),
  tags= ["staging","daily"]
)
}}

WITH plans AS (
  SELECT * FROM  {{source(var('source_schema', 'DEMO_STRIPE_NEW'), 'PLAN')}}
),
products AS (
  SELECT * FROM  {{source(var('source_schema', 'DEMO_STRIPE_NEW'), 'PRODUCT')}}
),
rename AS 
(
SELECT  
  --DLHK   
  MD5(plans.ID) AS K_PLAN_DLHK
  ,plans.ID AS K_PLAN_BK
  ,plans.PRODUCT_ID AS K_PRODUCT_BK
  ,plans.AGGREGATE_USAGE AS A_AGGREGATE_USAGE
  ,plans.BILLING_SCHEME AS A_BILLING_SCHEME
  ,plans.CREATED AS A_CREATED_AT
  ,plans.CURRENCY AS A_CURRENCY
  ,plans.INTERVAL AS A_INTERVAL
  ,plans.NICKNAME AS A_NICKNAME
  ,plans.TRANSFORM_USAGE_ROUND AS A_TRANSFORM_USAGE_ROUND
  ,plans.USAGE_TYPE AS A_USAGE_TYPE
  ,plans.TRANSFORM_USAGE_DIVIDE_BY AS A_TRANSFORM_USAGE_DIVIDE_BY
  ,products.CAPTION AS A_PRODUCT_CAPTION
  ,products.CREATED AS A_PRODUCT_CREATED_AT
  ,products.UPDATED AS A_PRODUCT_UPDATED_AT
  ,products.DESCRIPTION AS A_PRODUCT_DESCRIPTION
  ,products.NAME AS A_PRODUCT_NAME
  ,products.STATEMENT_DESCRIPTOR AS A_PRODUCT_STATEMENT_DESCRIPTOR
  ,products.TYPE AS A_PRODUCT_TYPE
  ,products.UNIT_LABEL AS A_PRODUCT_UNIT_LABEL
  ,products.URL AS A_PRODUCT_URL
  --BOOLEAN
  ,plans.ACTIVE AS B_ACTIVE
  ,plans.IS_DELETED AS B_IS_DELETED
  ,plans.LIVEMODE AS B_LIVEMODE  
  ,products.ACTIVE AS B_PRODUCT_ACTIVE
  ,products.IS_DELETED AS B_PRODUCT_IS_DELETED
  ,products.LIVEMODE AS B_PRODUCT_LIVEMODE
  ,products.SHIPPABLE AS B_PRODUCT_SHIPPABLE
  --METRICS
  ,plans.AMOUNT AS M_AMOUNT
  ,plans.INTERVAL_COUNT AS M_INTERVAL_COUNT
  ,plans.TRIAL_PERIOD_DAYS AS M_TRIAL_PERIOD_DAYS
  ,products.PACKAGE_DIMENSIONS_WIDTH AS K_PRODUCT_PACKAGE_DIMENSIONS_WIDTH
  ,products.PACKAGE_DIMENSIONS_HEIGHT AS M_PRODUCT_PACKAGE_DIMENSIONS_HEIGHT
  ,products.PACKAGE_DIMENSIONS_LENGTH AS M_PRODUCT_PACKAGE_DIMENSIONS_LENGTH
  ,products.PACKAGE_DIMENSIONS_WEIGHT AS M_PRODUCT_PACKAGE_DIMENSIONS_WEIGHT
  --METADATA
  , '{{invocation_id}}' as MD_INTGR_ID
  , CURRENT_TIMESTAMP() MD_ELT_UPDATED_DTS
FROM 
  plans
  LEFT JOIN products ON products.ID = plans.PRODUCT_ID
)

SELECT * FROM rename

