{{ config (
  materialized= 'view',
  schema= var('target_schema'),
  tags= ["staging","daily"]
)
}}

WITH charges AS (
  SELECT * FROM  {{source(var('source_schema', 'DEMO_STRIPE_NEW'), 'CHARGE')}}
),

rename AS 
(
SELECT  
    --DLHK
    MD5(C.ID) AS K_CHARGE_DLHK
    ,MD5(C.CUSTOMER) AS K_CUSTOMER_DLHK
    ,MD5(C.INVOICE) AS K_INVOICE_DLHK
    ,MD5(C.BALANCE_TRANSACTION) AS K_BALANCE_TRANSACTION_DLHK
    --BUSINESS KEYS
    ,C.ID AS K_CHARGE_BK
    ,C.CUSTOMER AS K_CUSTOMER_BK
    ,C.INVOICE AS K_INVOICE_BK    
    ,C.BALANCE_TRANSACTION AS K_BALANCE_TRANSACTION_BK
    --DESCRIPTION
    ,C.APPLICATION AS A_APPLICATION    
    ,C.CALCUATED_STATEMENT_DESCRIPTOR AS A_CALCULATED_STATEMENT_DESCRIPTOR
    ,C.CREATED::TIMESTAMP AS A_CREATED_AT
    ,C.CAPTURED::TIMESTAMP AS A_CAPTURED_AT
    ,C.CHARGE_ORDER AS A_CHARGE_ORDER       
    ,C.DESCRIPTION AS A_DESCRIPTION
    ,C.FAILURE_CODE AS A_FAILURE_CODE
    ,C.FAILURE_MESSAGE AS A_FAILURE_MESSAGE
    ,C.FRAUD_DETAILS_STRIPE_REPORT AS A_FRAUD_DETAILS_STRIPE_REPORT
    ,C.FRAUD_DETAILS_USER_REPORT AS A_FRAUD_DETAILS_USER_REPORT  
    ,C.ON_BEHALF_OF AS A_ON_BEHALF_OF
    ,C.RECEIPT_EMAIL AS A_RECEIPT_EMAIL
    ,C.RECEIPT_NUMBER AS A_RECEIPT_NUMBER
    ,C.RECEIPT_URL AS A_RECEIPT_URL
    ,C.REFUNDS_URL AS A_REFUNDS_URL
    ,C.SOURCE_TRANSFER AS A_SOURCE_TRANSFER
    ,C.STATEMENT_DESCRIPTOR AS A_STATEMENT_DESCRIPTOR
    ,C.STATUS AS A_STATUS
    ,C.TRANSFER_DATA_DESTINATION AS A_TRANSFER_DATA_DESTINATION
    ,C.TRANSFER_GROUP AS A_TRANSFER_GROUP
    --BOOLEAN
    ,C.DISPUTED AS B_DISPUTED
    ,C.LIVEMODE AS B_LIVEMODE
    ,C.REFUNDED AS B_REFUNDED
    ,C.PAID AS B_PAID
    ,C.REFUNDS_HAS_MORE AS B_REFUNDS_HAS_MORE    
    --METRICS
    ,C.CURRENCY AS A_CURRENCY
    ,C.AMOUNT AS M_AMOUNT
    ,C.AMOUNT_CAPTURED AS M_AMOUNT_CAPTURED
    ,C.AMOUNT_REFUNDED AS M_AMOUNT_REFUNDED
    ,C.APPLICATION_FEE AS M_APPLICATION_FEE
    ,C.APPLICATION_FEE_AMOUNT AS M_APPLICATION_FEE_AMOUNT
  --METADATA
  , '{{invocation_id}}' as MD_INTGR_ID
  , CURRENT_TIMESTAMP() MD_ELT_UPDATED_DTS
FROM 
  charges C
)

SELECT * FROM rename