{{ config (
  materialized= 'view',
  schema= var('target_schema'),
  tags= ["staging","daily"]
)
}}

WITH invoice AS (
  SELECT * FROM  {{source(var('source_schema', 'DEMO_STRIPE_NEW'), 'INVOICE_LINE_ITEM')}}
),
rename AS 
(
SELECT  
--DLHK
  MD5(ID) AS K_INVOICE_LINE_ITEM_DLHK
  ,MD5(INVOICE_ID) AS K_INVOICE_DLHK
  ,MD5(PLAN_ID) AS K_PLAN_DLHK
  ,MD5(SUBSCRIPTION_ID) AS K_SUBSCRIPTION_DLHK
  ,MD5(SUBSCRIPTION_ITEM_ID) AS K_SUBSCRIPTION_ITEM_DLHK
--BK
  ,ID AS K_INVOICE_LINE_ITEM_BK
  ,INVOICE_ID AS K_INVOICE_BK
  ,PLAN_ID AS K_PLAN_BK
  ,SUBSCRIPTION_ID AS K_SUBSCRIPTION_BK
  ,SUBSCRIPTION_ITEM_ID AS K_SUBSCRIPTION_ITEM_BK
  --ATTRIBUTES
  ,CURRENCY AS A_CURRENCY
  ,DESCRIPTION AS A_DESCRIPTION
  ,INVOICE_LINE_ITEM_TYPE AS A_INVOICE_LINE_ITEM_TYPE
  ,PERIOD_END AS A_PERIOD_END
  ,PERIOD_START AS A_PERIOD_START
  --BOOLEAN
  ,DISCOUNTABLE AS B_DISCOUNTABLE
  ,LIVEMODE AS B_LIVEMODE
  ,PRORATION AS B_PRORATION
  --METRICS
  ,AMOUNT AS M_AMOUNT
  ,QUANTITY AS M_QUANTITY
  --METADATA
  , '{{invocation_id}}' as MD_INTGR_ID
  , CURRENT_TIMESTAMP() MD_ELT_UPDATED_DTS
FROM 
  invoice I
)

SELECT * FROM rename