{{ config (
  materialized= 'view',
  schema= var('target_schema'),
  tags= ["staging","daily"]
)
}}

WITH invoice AS (
  SELECT * FROM  {{source(var('source_schema', 'DEMO_STRIPE_NEW'), 'INVOICE')}}
),
rename AS 
(
SELECT  
  --DLHK
  MD5(ID) AS K_INVOICE_DLHK
  ,MD5(CHARGE) AS K_CHARGE_DLHK
  ,MD5(CUSTOMER) AS K_CUSTOMER_DLHK
  ,MD5(SUBSCRIPTION) AS K_SUBSCRIPTION_DLHK
  --BK
  ,ID AS K_INVOICE_BK
  ,CHARGE AS K_CHARGE_BK
  ,CUSTOMER AS K_CUSTOMER_BK
  ,SUBSCRIPTION AS K_SUBSCRIPTION_BK
  --ATTRIBUTES
  ,CREATED AS A_CREATED
  ,ACCOUNT_COUNTRY AS A_ACCOUNT_COUNTRY
  ,ACCOUNT_NAME AS A_ACCOUNT_NAME
  ,BILLING_REASON AS A_BILLING_REASON
  ,CURRENCY AS A_CURRENCY  
  ,CUSTOMER_ADDRESS AS A_CUSTOMER_ADDRESS
  ,CUSTOMER_EMAIL AS A_CUSTOMER_EMAIL
  ,CUSTOMER_NAME AS A_CUSTOMER_NAME
  ,CUSTOMER_PHONE AS A_CUSTOMER_PHONE
  ,CUSTOMER_SHIPPING AS A_CUSTOMER_SHIPPING
  ,CUSTOMER_TAX_EXEMPT AS A_CUSTOMER_TAX_EXEMPT
  ,CUSTOM_FIELDS AS A_CUSTOM_FIELDS
  ,DUE_DATE AS A_DUE_DATE
  ,FOOTER AS A_FOOTER
  ,HOSTED_INVOICE_URL AS A_HOSTED_INVOICE_URL
  ,INVOICE_PDF AS A_INVOICE_PDF
  ,LAST_FINALIZATION_ERROR AS A_LAST_FINALIZATION_ERROR    
  ,TRANSFER_DATA AS A_TRANSFER_DATA
  ,WEBHOOKS_DELIVERED_AT::TIMESTAMP AS A_WEBHOOKS_DELIVERED_AT
  ,ACCOUNT_TAX_IDS AS A_ACCOUNT_TAX_IDS
  ,CUSTOMER_TAX_IDS AS A_CUSTOMER_TAX_IDS
  --BOOLEAN  
  ,ATTEMPTED AS B_ATTEMPTED
  ,AUTO_ADVANCE AS B_AUTO_ADVANCE
    --METRICS
  ,AMOUNT_PAID AS M_AMOUNT_PAID
  ,TOTAL_DISCOUNT_AMOUNTS AS M_TOTAL_DISCOUNT_AMOUNTS
  ,TOTAL_TAX_AMOUNTS AS M_TOTAL_TAX_AMOUNTS
  ,AMOUNT_DUE AS M_AMOUNT_DUE
  ,AMOUNT_REMAINING AS M_AMOUNT_REMAINING
  ,ATTEMPT_COUNT AS M_ATTEMPT_COUNT
  ,ENDING_BALANCE AS M_ENDING_BALANCE
  ,SUBTOTAL AS M_SUBTOTAL
  ,TAX AS M_TAX
  --METADATA
  , '{{invocation_id}}' as MD_INTGR_ID
  , CURRENT_TIMESTAMP() MD_ELT_UPDATED_DTS
FROM 
  invoice I
)

SELECT * FROM rename